source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RSPrescreener_Example', :exclusive => true do
  pod "RSPrescreener", :path => "../"
end

target 'RSPrescreener_Tests', :exclusive => true do
  pod "RSPrescreener", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
